import { Pill } from "./Badge.jsx";
import { Icon } from "./Icon.jsx";

const STATUS_TONE = {
  open: "blue",
  confirmed: "green",
  partial: "amber",
  closed: "gray",
  cancelled: "gray",
};

export function POTable({ pos, action, onReceive }) {
  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
        <div>
          <h1 className="text-display-lg font-headline-lg font-bold tracking-tight text-on-surface">
            Purchase Orders
          </h1>
          <p className="mt-1 text-body-sm font-body-sm text-on-surface-variant">
            Electronic POs generated by the agent, with confirmation and value tracking.
          </p>
        </div>
        {action}
      </div>

      {!pos?.length ? (
        <p className="rounded-xl border border-dashed border-outline-variant bg-surface-container-lowest p-6 text-center text-body-sm text-on-surface-variant">
          No purchase orders yet.
        </p>
      ) : (
        <div className="overflow-hidden rounded-xl border border-outline-variant bg-surface-container-lowest shadow-sm">
          <div className="w-full overflow-x-auto">
            <table className="w-full border-collapse text-left">
              <thead>
                <tr className="sticky top-0 z-10 border-b border-outline-variant bg-surface-container-low text-label-xs font-label-xs uppercase tracking-wider text-on-surface-variant">
                  <th scope="col" className="px-4 py-3 font-semibold">PO</th>
                  <th scope="col" className="px-4 py-3 font-semibold">SKU</th>
                  <th scope="col" className="px-4 py-3 font-semibold">Vendor</th>
                  <th scope="col" className="px-4 py-3 text-right font-semibold">Qty</th>
                  <th scope="col" className="px-4 py-3 text-right font-semibold">Confirmed</th>
                  <th scope="col" className="px-4 py-3 text-right font-semibold">Value</th>
                  <th scope="col" className="px-4 py-3 text-center font-semibold">Status</th>
                  <th scope="col" className="px-4 py-3 text-center font-semibold">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-outline-variant/60 font-body-md text-body-md">
                {pos.map((p) => (
                  <tr key={p.po_id} className="group transition-colors hover:bg-surface-container-low/60">
                    <td className="px-4 py-3.5 font-code-md text-code-md font-semibold text-secondary">
                      {p.po_id}
                    </td>
                    <td className="px-4 py-3.5 font-code-md text-code-md text-on-surface">{p.sku}</td>
                    <td className="px-4 py-3.5 text-on-surface">{p.vendor_id}</td>
                    <td className="px-4 py-3.5 text-right font-code-md text-code-md font-semibold text-on-surface">
                      {p.qty}
                    </td>
                    <td className="px-4 py-3.5 text-right font-code-md text-code-md text-on-surface-variant">
                      {p.confirmed_qty}
                    </td>
                    <td className="px-4 py-3.5 text-right font-code-md text-code-md text-on-surface">
                      {Math.round(p.order_value)}
                    </td>
                    <td className="px-4 py-3.5 text-center">
                      <Pill tone={STATUS_TONE[p.status] || "gray"}>{p.status}</Pill>
                    </td>
                    <td className="px-4 py-3.5 text-center">
                      {p.confirmed_qty < p.qty && p.status !== "cancelled" ? (
                        <button
                          onClick={() => onReceive?.(p)}
                          className="inline-flex items-center gap-1 rounded border border-outline-variant bg-surface-container px-2.5 py-1 text-label-xs font-label-xs text-on-surface transition-colors hover:bg-surface-container-high"
                        >
                          <Icon name="inventory" className="text-[14px]" />
                          Receive
                        </button>
                      ) : (
                        <span className="text-label-xs font-label-xs text-on-surface-variant">
                          —
                        </span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
